### ISSUE TITLE
Build script fails on Debian-based systems (sh vs. dash)

### ISSUE THREAD

**Issue by mbeckersys** [AdaCore/libadalang#11]
Hi,

Minor issue when running your script install-lal-and-deps.sh in Debian (or Ubuntu): Sourcing virtualenv fails, because /bin/sh is pointing to /bin/dash, where the command "source" is unknown.
Workaround: Change the interpreter to /bin/bash.

**Comment by pmderodat** [comment]
Hello @mbeckersys,

Thank you for reporting this issue. I opted for a change that should satisfy everybody: replacing the “source” command with the “.” one. It should work with all POSIX shells, and not force people to get a Bash interpreter if they don’t want to. ;-)
