### ISSUE TITLE
Obtaining the fully qualified name of a declaration

### ISSUE THREAD

**Issue by charlie5** [AdaCore/libadalang#13]
Is it possible to obtain the fully qualified name of a declaration ?

   For example, when parsing the 'Time' type in 'Ada.Calendar', is it possible to get 'Ada.Calendar.Time_Rep' for the parent type, instead of simply 'Time_Rep' ?

**Comment by raph-amiard** [comment]
Hi !
We don't support that functionality yet but it seems like a good idea to support it ! I'll keep this issue open in the meantime.

**Comment by raph-amiard** [comment]
@charlie5 Yes, it might be better if you wait until we transition to the new version of GNATColl. We'll keep you updated !

**Comment by charlie5** [comment]
:) ... will do.

Cheers.

**Comment by pmderodat** [comment]
Hello @charlie5,

The `P_Fully_Qualified_Name` property is now ready to use! You can see it in action in our testsuite: https://github.com/AdaCore/libadalang/blob/master/ada/testsuite/tests/properties/fully_qualified_name/test.py (code) and https://github.com/AdaCore/libadalang/blob/master/ada/testsuite/tests/properties/fully_qualified_name/test.out (expected output)

So we can finally close this issue… Cheers!
