### ISSUE TITLE
Errors installing library libadalang

### ISSUE THREAD

**Issue by KaizenBelmont** [AdaCore/libadalang#151]
I was trying to install libadalang using the script who recommend in this repository https://github.com/AdaCore/libadalang/blob/master/install-lal-and-deps.sh

Honestly, I made some modifications to the script to advance in the installation. I could get to the step when the script start to install libadalang and I get this errors:

![error1](https://user-images.githubusercontent.com/34594412/46434907-3c4fc680-c712-11e8-8197-0d875724b446.png)

![error2](https://user-images.githubusercontent.com/34594412/46434920-440f6b00-c712-11e8-8a8f-02cfdc1ee9de.png)

I was looking in the internet some information but I could not find much about it. Someone have some idea about it??

**Comment by KaizenBelmont** [comment]
basically, the biggest change that I made was in the file gnatcoll_iconv.gpr. I changed this line of code:
 Iconv_Opt := External ("GNATCOLL_ICONV_OPT", "-lc");
I put the parameter "-lc" becuase when I try to execute this part of code in the script:
    cd gnatcoll-bindings/iconv
    python2 setup.py build -j0 --prefix="$INSTALL_DIR"
    python2 setup.py install --prefix="$INSTALL_DIR"

In the line python2 setup.py build -j0 --prefix="$INSTALL_DIR", I get a error with the library -iconv. Searching in internet, I found in a forum that changed that parameter to -lc resolve the problem. 
Sincerely, I don't know what can do that part of code but this change, let myself to continue with the installation until the error I show you in the screen shot.

**Comment by pmderodat** [comment]
Understood. We are aware that `-liconv` should not be used on systems such as yours, where the libiconv is shipped inside the libc, so your changes look legitimate.

Can you check what version of Langkit you are using? The `install-lal-and-deps.sh` script creates a Python virtualenv called `lal-env` and installs the [most recent version](https://github.com/AdaCore/libadalang/blob/master/REQUIREMENTS.dev#L10), but as I said above, it seems that on your setup, an old version is used.

**Comment by KaizenBelmont** [comment]
I am new in linux and all this things...How can I see the version of Langkit?

**Comment by pmderodat** [comment]
Once pip installed it (through [this line](https://github.com/AdaCore/libadalang/blob/master/install-lal-and-deps.sh#L101)), I don’t know. I recommand you remove the `lal-env` directory and re-run the script.

**Comment by KaizenBelmont** [comment]
When I execute the script, print this:
Installing collected packages: langkit
Found existing installation: Langkit 0.1.dev0
Can't uninstall 'Langkit'. No files were found to uninstall.
Running setup.py develop for langkit
Successfully installed langkit

I think this "Langkit 0.1.dev0" is the version don't you?

**Comment by pmderodat** [comment]
I don’t understand where this comes from (there is no command to uninstall Langkit in the script) and I can’t reproduce myself. Have you tried removing the `lal-env` directory? (it’s inside the cloned `libadalang` repository)

**Comment by KaizenBelmont** [comment]
We are going to use another option, but thank you so much for the help.

**Comment by pmderodat** [comment]
Understood. I’ll close this issue considering that either the setup issue is on your side, either we’ll need a way to reproduce in order to fix anyway, but don’t hesitate to followup here if you decide to try again.

Good luck with your other option!
