### ISSUE TITLE
Only builds/installs relocatable library

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#174]
`ada/manage.py make` only builds the relocatable library.
`ada/manage.py install` only installs the relocatable library.

This isn’t the default expectation of libadalang-tools.

**Comment by simonjwright** [comment]
Pierre-Marie, I think that would be a good plan.
I certainly didn’t realise, even after this exchange, that I had to say

    ada/manage.py --enable-static build

rather than

    ada/manage.py build --enable-static

(of course, `install` needs to do both if necessary, so I see why you’ve done things the way you have).

**Comment by pmderodat** [comment]
Ok, thanks for the feedback, we’ll add a “build/test/install” section to the doc, then!

**Comment by pmderodat** [comment]
This is done now, so closing this. Thanks!
