### ISSUE TITLE
Building documentation on macOS

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#180]
I’m running with FSF GCC 9.0.0, but it seems unlikely I’d see anything different with CE?

After having built & installed libadalang, I tried building the documentation, & got
```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
making output directory...
ERROR: could not import Libadalang

Exception occurred:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libadalang.dylib, 6): image not found
```
Following the suggestion in the Developer manual, I tried
```
$ LD_LIBRARY_PATH=/opt/gcc-9.0.0/lib make html
```
with the same result.
What _did_ work was to run the command that `make html` called:
```
$  LD_LIBRARY_PATH=/opt/gcc-9.0.0/lib sphinx-build -b html -d _build/doctrees   . _build/html
```
On macOS we probably don’t need to do this for Ada executables, but we will have to do it for Python code that uses `dlopen()`.

----
In hindsight I should have said `make LD_LIBRARY_PATH=/opt/gcc-9.0.0/lib html`.
The `Makefile` could perhaps `export LD_LIBRARY_PATH`. Or, if undefined, determine it itself (`$prefix/lib`).

**Comment by pmderodat** [comment]
Hello Simon,

I have the feeling that this is due to a MacOS pecularity: `LIBRARY_PATH` is not propagated to subprocesses like other “regular” environment variables are. I think on this platform, specifying `DYLD_FALLBACK_LIBRARY_PATH` to be the same as `LIBRARY_PATH` should also work. I think I’ll update the build instructions accordingly.

**Comment by simonjwright** [comment]
Actually, LIBRARY_PATH is propagated from the environment; looks as though DYLD*, LD* are not. But what does seem to work without problem is `make LD_LIBRARY_PATH=/whatever ...`

**Comment by pmderodat** [comment]
Yes, sorry, I meant `LD_LIBRARY_PATH` instead of `LIBRARY_PATH`. Anyway, if `LD_LIBRARY_PATH` is propagated until the Python interpreter, I currently don’t understand why your first attempt does not work. To be investigated…

**Comment by simonjwright** [comment]
```
$  LD_LIBRARY_PATH=/opt/gcc-9.0.0/lib sphinx-build -b html -d _build/doctrees   . _build/html
```

worked because the `LD_LIBRARY_PATH` is in the environment that `sphinx-build` sees. But,

```
$ LD_LIBRARY_PATH=/opt/gcc-9.0.0/lib make html
```

fails because, although `make` sees the `LD_LIBRARY_PATH`, it doesn’t propagate it through to the `sphinx-build` call.

However, if we say `make LD_LIBRARY_PATH=/whatever`, it _does_ propagate it.

Could this be because `env`, or its libc equivalent, doesn’t propagate `LD_LIBRARY_PATH`?

```
$ LIBRARY_PATH=foo env | grep LIBRARY
LIBRARY_PATH=foo
$ LD_LIBRARY_PATH=foo env | grep LIBRARY
$ 
```

I just tried this on Linux; sure enough, this is indeed a Mac special. Possibly to do with System Integrity Protection.
