### ISSUE TITLE
SubpRenamingDecl not found as body

### ISSUE THREAD

**Issue by itoijala** [AdaCore/libadalang#195]
A `SubpRenamingDecl` can be the body of a `SubpDecl`, but this is not identified by libadalang. For example:

```ada
package Foo is
   procedure Bar;
end Foo;

package body Foo is
   procedure Baz is
   begin
      null;
   end Baz;

   procedure Bar renames Baz;
end Foo;
```

GPS correctly identifies the relationship between the declaration and the body and allows jumping between them.

A `decl_part` property should exist on `SubpRenamingDecl` and `body_part` on `SubpDecl` should find the renaming. `previous_part` and `next_part` should also be supported.

**Comment by itoijala-ssf** [comment]
The same applies to `NullSubpDecl`. The similar `ExprFunction` does work.
