### ISSUE TITLE
README doesn't clearly differentiate libadalang from ASIS

### ISSUE THREAD

**Issue by david-a-wheeler** [AdaCore/libadalang#2]
ASIS is widely used for static analysis of Ada code, and is an ISO standard (ISO/IEC 15291:1995).

The README does not make it clear why I'd use libadalang instead of ASIS, and it really needs to provide that info.  The ASIS spec may not include some of the latest Ada features, but I presume that they'd be easy to add.  Why would I use libadalang instead?

**Comment by pmderodat** [comment]
Hi @david-a-wheeler,

Even This is a good idea. We have started to work on this, we’ll keep you updated. Thank you!

**Comment by raph-amiard** [comment]
Hello David,

We have updated the readme with more information. Tell us what you think !

**Comment by david-a-wheeler** [comment]
Much better, however, most software developers don't know what a "semantic engine" is - you should define terms like that if you use them.
