### ISSUE TITLE
Offer latest documentation via web

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/libadalang#240]
Why not generate the html documentation of the latest version and provide it to your users?

I am already struggling for a day just to get it....

**Comment by pmderodat** [comment]
Hello,

We do generate HTML documentation: <http://docs.adacore.com/live/wave/libadalang/html/libadalang_ug/index.html>. It corresponds to the `stable` branch, which is would we advise you to use, the `master` one being the development one. Your message makes me realize that we should probably include the above URL in our README… thanks for the note!

**Comment by pjljvandelaar** [comment]
Is only the user manual generated or also the developer documentation?

**Comment by pmderodat** [comment]
Only the user manual. As you can quickly see from its sources, the dev manual does is very incomplete, but there is little chance that you would need to read it anyway. Out of curiosity, what are you trying to do with Libadalang?

**Comment by pjljvandelaar** [comment]
I would like to get dependencies  from an ada code base
as input for a generic code analyzer.
That generic code analyzer is already applied on C, C++ and C# code.

**Comment by pmderodat** [comment]
Ok, thanks for the context! So the user manual is definitely what you should read, and the dev manual will be useless.
