### ISSUE TITLE
On using libadalang

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/libadalang#241]
On windows, I have installed `gnatpro-19.1-x86_64-windows-bin` and `gps-19.1-x86_64-windows-bin`. Consequently, I have in `C:\GNATPRO\19.1\bin\gps.libadalang` the library `libadalang.dll`.

So I added that path to `libadalang` my `PYTHONPATH`,
as can be seen from
```
PS C:\> python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print (sys.path)
['', 'C:\\GNATPRO\\19.1\\bin\\gps.libadalang', 'C:\\Users\\laarpjljvd\\AppData\\Local\\Programs\\Python\\Python37\\python37.zip', 'C:\\Users\\laarpjljvd\\AppData\\Local\\Programs\\Python\\Python37\\DLLs', 'C:\\Users\\laarpjljvd\\AppData\\Local\\Programs\\Python\\Python37\\lib', 'C:\\Users\\laarpjljvd\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\laarpjljvd\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
>>>
```
However, `import libadalang` gives
```
>>> import libadalang
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'libadalang'
>>>
```

Am I doing something wrong? I think I have followed all documentation I could find....

**Comment by pmderodat** [comment]
As you are using GNAT Pro 19.1, it seems that you are a supported AdaCore customer: please go through GNATtracker to open a ticket. Thank you in advance!

**Comment by afaucon** [comment]
Hello,
Same question but with GNAT Community.
(gnat-community-2019-20190517-x86_64-windows-bin.exe)

How to use libadalang with a python interpreter (version 3.7 for example) different from the python 2 interpreter that comes with the gnat installer?

Can this issue be reopened?
Regards,
Adrien

**Comment by pmderodat** [comment]
Hello,

This looks like a completely different question to me. ;-)

Although we have plans to add support for Python 3, we haven’t been able to schedule work on this so far. We hope to do it before Python2’s end of maintenance, but no promise…
