### ISSUE TITLE
documentation on supported Ada/python versions

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/libadalang#254]
On the homepage is written
```
Libadalang is a library that can be used from Ada and Python. Most of its code is Ada code, generated from the language specification that you can find in ada/language.
```
[Python has multiple versions](https://wiki.python.org/moin/Python2orPython3) and from this description it is not clear which python versions are supported.
Similar Ada also has multiple versions.
As a user, I would like to know 
* whether there are requirements on the version of Ada and python.
     e.g. is a minimal version required or can I even use python1.x?
* are versions no longer supported (like python 2.6.x or 1.x)?
* with which versions libadalang is tested.

**Comment by raph-amiard** [comment]
Hi @pjljvandelaar, and sorry for the lag in answering you.

Only Python 2.x is supported for the moment, however we plan to support Python 3 soon-ish.

As far as Ada:

1. The generated library is Ada 2012, so requires a pretty recent Ada compiler (only GNAT is fully Ada 2012 compliant AFAICT)

2. Libadalang itself is capable of analyzing Ada code from any ada versions, from 83 to 2012.

**Comment by raph-amiard** [comment]
Hi @pjljvandelaar, we clarified the doc. For info, we'll be working on Python 3 support in the next release cycle. You can check #325 for any update.
