### ISSUE TITLE
Anybody try to build on Windows? quex error duting 'generate'

### ISSUE THREAD

**Issue by MattBorchers** [AdaCore/libadalang#27]
Has anybody tried building on Windows?  I get the following output in a Windows command shell which errors in trying to execute quex-exe.py.  Perhaps it is all the double slashes since it seems like this script expects to be running in a *nix environment?

c:\Users\Matt\Downloads\AdaCore-Download-2017-11-16_1312\libadalang-master>c:\Python27\python.exe .\ada\manage.py generate
[95mGenerating source for libadalang...[0m
[94mCompiling the grammar...[0m
[94mCompiling properties...[0m
[94mPrepare code emission...[0m
[94mFile setup...[0m
[94mGenerating sources... [0m
[94mCompiling the quex lexer specification[0m
command line: Command line option '--token-memory-management-by-user' is ignored.
command line: User token memory management option no longer available.
command line: Last version of Quex supporting this option is version 0.67.4. Please, visit
command line: http://quex.org for further information.
    [1m[91mError[0m: Command '['c:\\Python27\\python.exe', 'C:\\Program Files (x86)\\quex/quex-0.67.5/quex-exe.py', '-i', 'c:\\Users\\Matt\\Downloads\\AdaCore-Download-2017-11-16_1312\\libadalang-master\\build\\include\\libadalang\\ada.qx', '-o', 'quex_lexer', '--buffer-element-size', '4', '--token-id-offset', '0x1000', '--language', 'C', '--no-mode-transition-check', '--single-mode-analyzer', '--token-memory-management-by-user', '--token-policy', 'single', '--token-id-prefix', 'ADA_TKN_']' returned non-zero exit status -1
[91mInternal error! Exiting[0m

**Comment by raph-amiard** [comment]
Hello Matt,

I think the problem you have is exactly what is described by Quex: your version of quex is too recent.

As explained in our README:

    Install Quex version 0.65.4 - http://downloads.sourceforge.net/project/quex/DOWNLOAD/quex-0.65.4.tar.gz Follow the installation guide in the Quex README

We should update to Quex latest version someday, but for the moment this works fine and we have higher priority items to tackle :)

Please open other issues if you stumble upon other build problems !
