### ISSUE TITLE
License of withed unit "GNATCOLL.Refcount" may be inconsistent.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/libadalang#298]
Hello,

I've the following issue with libadalang:
```
[Ada] langkit_support-tree_traversal_iterator.adb
langkit_support-tree_traversal_iterator.ads:24:14: warning: license of withed unit "GNATCOLL.Refcount" may be inconsistent
compilation of langkit_support-tree_traversal_iterator.adb failed
```
Is there a way to avoid warning processed as errors?
Maybe manage.py might support --gpr-opts as GnatColl do.
In this manner, --gpr-opts=-gnatwn might be added on the command line.

As advice by Pierre-Marie (https://github.com/AdaCore/libadalang-tools/issues/4), I rebuild from Github sources all dependancies with no success. And I want to keep compilation in debug mode.

My configuration: GNAT Community 2019 on macOS 10.13.6.

Thanks, Pascal.

**Comment by pmderodat** [comment]
Hello,

I suspect there is something wrong in your setup, as this is what we do in our Travis setup (see for instance these logs: https://travis-ci.org/AdaCore/libadalang/jobs/569437654) without any problem. If that helps, you can find [the corresponding scripts](https://github.com/AdaCore/libadalang/blob/master/install-lal-and-deps.sh).

Or you can try manage.py’s `--gargs` option: `ada/manage.py build --gargs=-gnatwn`.
