### ISSUE TITLE
checking formal parameters

### ISSUE THREAD

**Issue by briot** [AdaCore/libadalang#316]
If I have a TypeDecl node, I can find whether it is defined in a generic package by looking at whether its `p_semantic_parent` is a `GenericPackageDecl` (or so I have done so far, there might be better solutions).

But I am not sure how to reliably check whether this typedecl is a formal parameter of the package, or just defined in the spec of the package.

Any ideas on the subject ?

Thanks in advance

**Comment by raph-amiard** [comment]
You can check whether the syntactic parent is a `GenericFormalDecl`:

```
decl.parent.is_a(lal.GenericFormalDecl)
```

We have such a property internally, I'll add it to the public API

**Comment by briot** [comment]
I just realized I had something similar already. The more complex part now is: how do I check whether it comes from a formal package parameter. But I think this is just a multi-step test, so I should manage. Thanks !

**Comment by briot** [comment]
In one of my tests, the parent was `GenericFormalTypeDecl`.
Was this a typo in your message, or are there in fact multiple possibilities for the parent ?

**Comment by raph-amiard** [comment]
I'll keep the issue open to track adding the public property :slightly_smiling_face: 

Basically:

`GenericFormalDecl` is the base class for generic formal enclosing decls. The real decl is *inside*, accessible via the `f_decl` field.

`GenericFormalTypeDecl` is a subclass of `GenericFormalDecl`, basically telling you that it's wrapping a type decl, so you know that `f_decl` will be a `BaseTypeDecl`.

**Comment by raph-amiard** [comment]
It's done!
