### ISSUE TITLE
Missing resolution on “package body FOO”

### ISSUE THREAD

**Issue by pmderodat** [AdaCore/libadalang#32]
Running the following script reveals a hole in the name resolution:

```py
import libadalang as lal
ctx = lal.AnalysisContext()
ctx.get_from_buffer('foo.ads', '''
package Foo is
    procedure P;
end Foo;
''')
u = ctx.get_from_buffer('foo.adb', '''
package body Foo is
    procedure P is null;
end Foo;
''')

p = u.root.find(lal.Identifier)
print('{} -> {}'.format(p, p.p_referenced_decl))
```

That yields a `Property_Error` whereas it should print the node for “package Foo”.

**Comment by raph-amiard** [comment]
This has been sorted out now: Basically you cannot call `p_referenced_decl` on a defining name.If you want to go to the decl, you need to call `p_previous_part` on the defining identifier.
