### ISSUE TITLE
Name resolution for procedure declarations

### ISSUE THREAD

**Issue by pmderodat** [AdaCore/libadalang#33]
Running `nameres --all --with-default-project pck.ads` on the following source file:

```ada
with GNAT.Regexp;

package Pck is
   procedure P1 (I : Integer);
   procedure P2 (R : GNAT.Regexp.Regexp);

   procedure P3 (IA : access Integer);
   procedure P4 (RA : access GNAT.Regexp.Regexp);
end Pck;
```
Yields odd results:
* There is no resolution for `P1` nor `P2`.
* `Integer` from P3 is correctly resolved.
* Various intermediate nodes in `access GNAT.Regexp.Regexp` are not resolved:
```Resolving xrefs for node <AnonymousTypeDecl ["None"] 8:23-8:48>
***************************************************************

Expr: <DottedName 8:30-8:48>
  references: <TypeDecl ["Regexp"] 103:4-103:27>
  type:       None
Expr: <DottedName 8:30-8:41>
  references: None
  type:       None
Expr: <Id "GNAT" 8:30-8:34>
  references: None
  type:       None
Expr: <Id "Regexp" 8:35-8:41>
  references: None
  type:       None
Expr: <Id "Regexp" 8:42-8:48>
  references: <TypeDecl ["Regexp"] 103:4-103:27>
  type:       None
```

**Comment by raph-amiard** [comment]
I ran it today, and everything seems fine now: 

	Analyzing pck.ads
	#################

	Resolving xrefs for node <WithClause 1:1-1:18>
	**********************************************

	Expr: <DottedName 1:6-1:17>
	  references: <PackageRenamingDecl ["GNAT.Regexp"] 70:1-70:43>
	  type:       None
	Expr: <Id "GNAT" 1:6-1:10>
	  references: <PackageDecl ["GNAT"] 34:1-37:10>
	  type:       None
	Expr: <Id "Regexp" 1:11-1:17>
	  references: <PackageRenamingDecl ["GNAT.Regexp"] 70:1-70:43>
	  type:       None

	Resolving xrefs for node <SubpSpec 4:4-4:30>
	********************************************

	Expr: <Id "P1" 4:14-4:16>
	  references: None
	  type:       None

	Resolving xrefs for node <ParamSpec ["I"] 4:18-4:29>
	****************************************************

	Expr: <Id "I" 4:18-4:19>
	  references: None
	  type:       None
	Expr: <Id "Integer" 4:22-4:29>
	  references: <TypeDecl ["Integer"] 4:3-4:54>
	  type:       None

	Resolving xrefs for node <SubpSpec 5:4-5:41>
	********************************************

	Expr: <Id "P2" 5:14-5:16>
	  references: None
	  type:       None

	Resolving xrefs for node <ParamSpec ["R"] 5:18-5:40>
	****************************************************

	Expr: <Id "R" 5:18-5:19>
	  references: None
	  type:       None
	Expr: <DottedName 5:22-5:40>
	  references: <TypeDecl ["Regexp"] 103:4-103:27>
	  type:       None
	Expr: <DottedName 5:22-5:33>
	  references: <PackageRenamingDecl ["GNAT.Regexp"] 70:1-70:43>
	  type:       None
	Expr: <Id "GNAT" 5:22-5:26>
	  references: <PackageDecl ["GNAT"] 34:1-37:10>
	  type:       None
	Expr: <Id "Regexp" 5:27-5:33>
	  references: <PackageRenamingDecl ["GNAT.Regexp"] 70:1-70:43>
	  type:       None
	Expr: <Id "Regexp" 5:34-5:40>
	  references: <TypeDecl ["Regexp"] 103:4-103:27>
	  type:       None

	Resolving xrefs for node <SubpSpec 7:4-7:38>
	********************************************

	Expr: <Id "P3" 7:14-7:16>
	  references: None
	  type:       None

	Resolving xrefs for node <ParamSpec ["IA"] 7:18-7:37>
	*****************************************************

	Expr: <Id "IA" 7:18-7:20>
	  references: None
	  type:       None
	Expr: <Id "Integer" 7:30-7:37>
	  references: <TypeDecl ["Integer"] 4:3-4:54>
	  type:       None

	Resolving xrefs for node <SubpSpec 8:4-8:49>
	********************************************

	Expr: <Id "P4" 8:14-8:16>
	  references: None
	  type:       None

	Resolving xrefs for node <ParamSpec ["RA"] 8:18-8:48>
	*****************************************************

	Expr: <Id "RA" 8:18-8:20>
	  references: None
	  type:       None
	Expr: <DottedName 8:30-8:48>
	  references: <TypeDecl ["Regexp"] 103:4-103:27>
	  type:       None
	Expr: <DottedName 8:30-8:41>
	  references: <PackageRenamingDecl ["GNAT.Regexp"] 70:1-70:43>
	  type:       None
	Expr: <Id "GNAT" 8:30-8:34>
	  references: <PackageDecl ["GNAT"] 34:1-37:10>
	  type:       None
	Expr: <Id "Regexp" 8:35-8:41>
	  references: <PackageRenamingDecl ["GNAT.Regexp"] 70:1-70:43>
	  type:       None
	Expr: <Id "Regexp" 8:42-8:48>
	  references: <TypeDecl ["Regexp"] 103:4-103:27>
	  type:       None

So closing this now !
