### ISSUE TITLE
Wrong set of literals for Standard.Character

### ISSUE THREAD

**Issue by briot** [AdaCore/libadalang#333]
When I look at the properties for the node corresponding to Standard.Character, I get a wrong list of literals:

```
=== Dump: <EnumTypeDef 20:21-20:26>
  inheritance tree: ['EnumTypeDef', 'TypeDef', 'AdaNode', 'object']
  methods:          ['cast', 'iter_fields', 'lookup', 'p_filter_is_imported_by', 'p_referenced_decl', 'p_std_entity', 'p_top_level_decl', 'p_xref', 'to_data', 'to_json']
  child_index       : 2
  children          : [<EnumLiteralDeclList 20:22-20:25>]
  entity_repr       : <EnumTypeDef 20:21-20:26>
  f_enum_literals   : <EnumLiteralDeclList 20:22-20:25>
  kind_name         : EnumTypeDef
  p_body_unit       : <AnalysisUnit 'standard.adb'>
  p_semantic_parent : <TypeDecl ["Character"] 20:3-20:27>
  p_standard_unit   : <AnalysisUnit '__standard'>
  parent            : <TypeDecl ["Character"] 20:3-20:27>
  parent_chain      : [<EnumTypeDef 20:21-20:26>, <TypeDecl ["Character"] 20:3-20:27>, <AdaNodeList 2:1-120:42>, <PublicPart 1:20-121:1>, <PackageDecl ["Standard"] 1:1-121:14>, <LibraryItem 1:1-121:14>, <CompilationUnit 1:1-121:14>]
  parents           : [<EnumTypeDef 20:21-20:26>, <TypeDecl ["Character"] 20:3-20:27>, <AdaNodeList 2:1-120:42>, <PublicPart 1:20-121:1>, <PackageDecl ["Standard"] 1:1-121:14>, <LibraryItem 1:1-121:14>, <CompilationUnit 1:1-121:14>]
  previous_sibling  : None
  short_image       : <EnumTypeDef 20:21-20:26>
  sloc_range        : 20:21-20:26
  text              : ('A')
  token_end         : <Token Par_Close u')' at 20:25-20:26>
  token_start       : <Token Par_Open u'(' at 20:21-20:22>
  tokens            : <generator object tokens at 0x14a84e5a02d0>
  unit              : <AnalysisUnit '__standard'>
```

(look at the `text` attribute for instance, though my script uses `f_enum_literals` which also only contains "A")

**Comment by pmderodat** [comment]
Hello @briot,

This is expected: we don’t materialize the various enumerators for `Character`, `Wide_Character` and `Wide_Wide_Character`. This would create memory consumption issues for the last two. So instead we just provide stub definitions such as `type Character is ('A');`.

Working around this should be easy, though: create special case that detect they are working on these standard type and do the processing you need based on either the enumerator you have at hand (`'A'`, `'É'`, …).

I hope that helps,

**Comment by briot** [comment]
> This is expected: we don’t materialize the various enumerators for Character, Wide_Character and Wide_Wide_Character. This would create memory consumption issues for the last two. So instead we just provide stub definitions such as type Character is ('A');.

I did not find that in the documentation, where is it ?

Could it perhaps be a generator in python ? We do not have to consume memory for this, indeed.

> Working around this should be easy, though: create special case that detect they are working on these standard type and do the processing you need based on either the enumerator you have at hand ('A', 'É', …).

Workarounds are easy, I just special case them in my script. But that’s not elegant…

Thanks
Manu

**Comment by raph-amiard** [comment]
> Could it perhaps be a generator in python ? We do not have to consume memory for this, indeed.

Well if you start consuming the list of literals for `Wide_Wide_Character`, you will actually use this memory. So you don't have a solution (in this case) except making a special case from what I can see.

Also, those literals would have no real source existence, unlike every other literal in the language, so this would be a bit weird.

I agree that the current solution is a bit of a hack (there is no reason that there would be only one literal, and for it to be `'A'`), but I guess that it is a result of the fact that we don't really know how to do it cleanly.
