### ISSUE TITLE
Name resolution: xrefs for generic instantiations

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/libadalang#35]
For the moment we're not name resolving anything in generic instantiations.
Opening this issue to track the work of implementing what's needed to resolve
names in generic instantiations.

**Comment by briot** [comment]
I think this is related. Here's the example I was trying to use:

```ada
package Main is

   generic
      type T is private;
   package Pkg is
      type My_T is new Integer;
   end Pkg;

   package Pkg_Integer is new Pkg (Integer);

   type Rec3 is record
      Field1 : Pkg_Integer.Rec;    --  analyze this line
   end record; 

end Main;
```

Looking at the parent nodes for  `Rec`, I am getting, in python:

```
<EntityArray [<TypeDecl ["Rec"] 23:7-26:19>, <AdaNodeList 23:7-26:19>, <PublicPart 23:7-26:19>, <GenericPackageInternal ["Pkg"] 22:4-27:12>, <GenericPackageDecl ["Pkg"] 20:4-27:12>, <AdaNodeList 5:4-34:43>, <DeclarativePart 5:4-34:43>, <SubpBody ["Main"] 3:1-38:10>, <LibraryItem 3:1-38:10>, <CompilationUnit 1:1-38:10>]>
```

which indeed does not show the generic instance, so I can't know this is from `Pkg_Integer` (just that it is from an instance of `Pkg`

Is this what this issue is about ?

**Comment by pmderodat** [comment]
Hello Manu,

No, this is not what this ticket is about. :-) But indeed we miss a way for an entity to retrieve the list of generics instantiations that created it. We think we should expose a property to provide this information: I’ve just opened #47 to work on that.

**Comment by briot** [comment]
> No, this is not what this ticket is about. :-) But indeed we miss a way for an entity to retrieve the list of generics instantiations that created it. We think we should expose a property to provide this information: I’ve just opened #47 to work on that.


Thanks PM, that’s really helpful !
Looking forward to it :-)

Manu
