### ISSUE TITLE
invalid column information when source file contains tabulation characters

### ISSUE THREAD

**Issue by jotd666** [AdaCore/libadalang#4]
I tried to insert statements before a null; statement that was indented by 2 tabulation chars, and the insertion position that was given was incorrect, resulting in an insertion in the middle of the null word.

workaround: replaced tabulation chars by 4 spaces (any number would be OK) and it inserted the statement properly, so not blocking but you may want to look into this.

**Comment by raph-amiard** [comment]
Hello @jotd666, thank you for the report.

We are indeed aware of the issue with tabs. It is pretty low priority for us since a large portion of Ada code bases indent with spaces, but we do intend to fix this at some point. We'll keep you updated !

**Comment by pmderodat** [comment]
Hello @jotd666 

This is now implemented! With Libadalang and Langkit’s current master branch, you can now pass the tab stop to the `Analysis_Context` constructor (both in Ada and Python APIs), and it is then used to compute the column offset for tab character in sources.

**Comment by pmderodat** [comment]
Sure, see you! :-)
