### ISSUE TITLE
check_useless_assign.py linter is case sensitive on identifiers

### ISSUE THREAD

**Issue by DuncanSands** [AdaCore/libadalang#40]
This linter warned about the assignment on the next line, saying the value is never used:

            Next_Local_Start_Time := Truncate_To_Day(Next_Local_Start_Time) + Input_Start_Hour;
         end if;

         Next_Start_Time := Time_Zones.Convert(T => Next_Local_Start_time,

^ But it was used immediately after.  However the identifiers were capitalized differently (..._Time vs ..._time) which must have confused the linter.

**Comment by raph-amiard** [comment]
@DuncanSands this checker is only provided as a demo, and @yannickmoy hasn't looked at it yet. If you're looking for up to date checkers, [codepeer](https://www.adacore.com/codepeer) contains more up-to-date versions of those.
