### ISSUE TITLE
install-lal-and-deps.sh fails with "unable to resolve host address"

### ISSUE THREAD

**Issue by MaxBarraclough** [AdaCore/libadalang#430]
The script fails with the following message:

    --2020-01-24 23:53:45--  http://mirrors.cdn.adacore.com/art/5cdffc5409dcd015aaf82626
    Resolving mirrors.cdn.adacore.com (mirrors.cdn.adacore.com)... failed: Name or service not known.
    wget: unable to resolve host address ‘mirrors.cdn.adacore.com’
    ubuntu@myhost:~/downloads/libadalang$ curl mirrors.cdn.adacore.com
    curl: (6) Could not resolve host: mirrors.cdn.adacore.com

Also, the script uses insecure HTTP URLs.

**Comment by pmderodat** [comment]
Hello @MaxBarraclough,

Thank you for reporting this! A fix is in the pipes…

**Comment by pmderodat** [comment]
This should now be fixed on the `master` branch. Thanks again!
