### ISSUE TITLE
Name resolution for subtypes

### ISSUE THREAD

**Issue by briot** [AdaCore/libadalang#46]
Given the following package:

```ada
with Ada.Calendar;   use Ada.Calendar;
package Main is
   package Nested is
      subtype My_Time is Time;
   end Nested;
   use Nested;
   type T is record
      Field1 : My_Time;
   end record;
end Main;
```

I am using python code like:

```python
for d in unit.root.findall(SubtypeDecl):     # declaration of MyType
      print decl.f_subtype.f_name   # <Identifier>         
      print decl.f_subtype.f_name.p_referenced_decl     # Internal error
```

It raises an internal error:

```
  File "/usr/local/stow/libadalang/python/libadalang.py", line 785, in p_referenced_decl
    return AdaNode._wrap(self._eval_field(Entity._c_type(), _ada_node_p_referenced_decl))
  File "/usr/local/stow/libadalang/python/libadalang.py", line 1178, in _eval_field
    raise PropertyError(*exc.contents._wrap().args)
libadalang.PropertyError: raised LIBADALANG.ANALYSIS.PROPERTY_ERROR : dereferencing a null access
```

**Comment by briot** [comment]
Misunderstanding on my part, I think.

Using `.p_name_designated_type` instead of `.p_referenced_decl` works.
I am not clear when to use one or the other, but I am sure the documentation will be improved at some point.
Closing this issue...

**Comment by raph-amiard** [comment]
Hello Manu!

Well you were right the first time around :) We actually want p_referenced_decl to work in this case.

SubtypeIndication.p_designated_type and Name.p_name_designated_type actually work too, but referenced_decl applies in this case, so this is indeed a bug (or rather a hole in the feature ^^) Will fix ASAP.

**Comment by raph-amiard** [comment]
Fixed !
