### ISSUE TITLE
Name resolution: properties to retrieve context instantiations

### ISSUE THREAD

**Issue by pmderodat** [AdaCore/libadalang#47]
As explained [here](https://github.com/AdaCore/libadalang/issues/35#issuecomment-351936791), it would be useful to have properties on entities to retrieve the list of generic instanciation that lead to the creation of the said entity.

**Comment by pmderodat** [comment]
Hello @briot,

I think the feature you asked for in #35 is now implemented. In Libadalang, everybody can now use the `P_Generic_Instantiations` property to get the list of generic package/subprogram instantiations that led to the creation of an entity. See the testcase in 59f01a2802143a2abb5362be8eb53adb48653708 for an example of how to use it.

Cheers!

**Comment by briot** [comment]
I confirm this works as expected ! Thanks, that was very fast. Shows that libadalang has some seriously good basis in there :-)

**Comment by pmderodat** [comment]
Awesome, and thank you for your feedback! :-)
