### ISSUE TITLE
Name resolution: Bug with subtype declarations

### ISSUE THREAD

**Issue by Roldak** [AdaCore/libadalang#48]
```Ada
procedure Test is
   subtype Natural is Integer range 0 .. Integer'Last;
   x : Integer := Natural'First;
begin
   null;
end Test;
```

Getting a `libadalang.PropertyError: raised LIBADALANG.ANALYSIS.PROPERTY_ERROR : dereferencing a null access` error when trying to get property `p_expression_type` on the literal `0` appearing in the subtype declaration.

**Comment by raph-amiard** [comment]
Duplicate of #46 I think

**Comment by raph-amiard** [comment]
Fixed
