### ISSUE TITLE
leading comment left out of "unit.root.text"

### ISSUE THREAD

**Issue by jotd666** [AdaCore/libadalang#5]
when parsing a file, the "text" member applied on root node provides the full source code, including comments, except for the leading comments (the ones before the first valid Ada token).

Again, I can workaround it by managing my list of lines in another buffer.

**Comment by raph-amiard** [comment]
Hello @jotd666, thank you very much for the report,

We'll look at it, we have support for tokenizing and storing comments, but the special case for the text of the top-level node must not have been implemented !

**Comment by pmderodat** [comment]
Hi @jotd666,

Tell me if I’m wrong: I’m assuming you are using the Python API.

Comments do not contribute to the parsing on AST nodes, so it’s part of our design that comments before/after the first/last token are not returned by the `text` method. For instance:
```ada
--  Before
A : Integer
--  After
```
The first token of this object declaration is the `A` identifier, the last one is the `Integer` identifier, so `text` must return only tokens from the former to the latter, excluding comments around.

Now, there actually is  way to get all the text you want:
* `libadalang.AnalysisUnit.first_token` and `last_token` are properties that return the first/last tokens for the whole analysis unit (including comments);
* `libadalang.Token.text_range` takes two tokens and returns the source text that covers these tokens and all tokens in between.

Here is a script that demonstrate the difference with `unit.root.text`:
```python
import libadalang as lal

src_buffer = """
--  Before
procedure Foo is
begin
   null; --  Inside
end Foo;
--  After
"""

ctx = lal.AnalysisContext()
unit = ctx.get_from_buffer('foo.adb', src_buffer, with_trivia=True)

print 'With .text:'
print unit.root.text
print

print 'With .text_range:'
print lal.Token.text_range(unit.first_token, unit.last_token)
```
On a simple example source, the above script yields:
```
With .text:
procedure Foo is
begin
   null; --  Inside
end Foo;

With .text_range:
--  Before
procedure Foo is
begin
   null; --  Inside
end Foo;
--  After
```
