### ISSUE TITLE
libadalang.PropertyError: dereferencing a null access

### ISSUE THREAD

**Issue by GUIpsp** [AdaCore/libadalang#531]
Stacktrace is as follows:
```
(cut)
  File "/home/guipsp/PycharmProjects/libtest/ada_visitor.py", line 198, in name_with_imports
    pkg = node.p_called_subp_spec
  File "/home/guipsp/libadalang/build/python/libadalang/__init__.py", line 9368, in p_called_subp_spec
    c_result = self._eval_field(_Entity_c_type(), _name_p_called_subp_spec)
  File "/home/guipsp/libadalang/build/python/libadalang/__init__.py", line 2254, in _eval_field
    if not c_accessor(*args):
  File "/home/guipsp/libadalang/build/python/libadalang/__init__.py", line 82, in wrapper
    raise exc.contents._wrap()
```

The code being parsed is from here: http://rosettacode.org/wiki/Sorting_algorithms/Quicksort#Ada

The error occurs on getting the property `node.p_called_subp_spec` on the `CallExpr` that represents `Sort_Days(Weekly_Sales)`.

Thanks, and let me know if you require any more info.

**Comment by Roldak** [comment]
Hi Guilherme!

I think it's because there is a missing `with Quick_Sort` clause in that example.
After adding it at the top of `sort_test.adb`, the property call was successful:

```
>> c = u.root.findall(lal.CallExpr)[-2]
>> c.text
'Sort_Days(Weekly_Sales)'
>> c.p_called_subp_spec
<SubpSpec quick_sort.ads:9:1-9:47>
```

I'll close this, don't hesitate to reopen if you're still having issues!

**Comment by GUIpsp** [comment]
Hello,

That wasn't quite the issue, however, that lead me in the right direction: I hadn't named the files exactly according to the unit name. Renaming the files fixed the issue for me.
