### ISSUE TITLE
unknown project file: "gnatcoll"

### ISSUE THREAD

**Issue by xgdfalcon** [AdaCore/libadalang#553]
I installed everything on a fresh CentOS 8 installation

Everything went well.

When I try the tutorial https://github.com/AdaCore/libadalang/blob/master/user_manual/ada_api_tutorial.rst
I get errors bellow

```
using project file lal_test.gpr
libadalang.gpr:12:06: unknown project file: "gnatcoll"
libadalang.gpr:12:06: imported by "/opt/gnatstudio/share/gpr/libadalang.gpr"
libadalang.gpr:12:06: imported by "/home/xgdfalcon/source/generate_schemas/lal_test.gpr"
langkit_support.gpr:10:06: unknown project file: "gnatcoll"
langkit_support.gpr:10:06: imported by "/opt/gnatstudio/share/gpr/langkit_support.gpr"
langkit_support.gpr:10:06: imported by "/opt/gnatstudio/share/gpr/libadalang.gpr"
langkit_support.gpr:10:06: imported by "/home/xgdfalcon/source/generate_schemas/lal_test.gpr"
gnatcoll_iconv.gpr:9:06: unknown project file: "gnatcoll"
gnatcoll_iconv.gpr:9:06: imported by "/opt/gnatstudio/share/gpr/gnatcoll_iconv.gpr"
gnatcoll_iconv.gpr:9:06: imported by "/opt/gnatstudio/share/gpr/langkit_support.gpr"
gnatcoll_iconv.gpr:9:06: imported by "/opt/gnatstudio/share/gpr/libadalang.gpr"
gnatcoll_iconv.gpr:9:06: imported by "/home/xgdfalcon/source/generate_schemas/lal_test.gpr"
gnatcoll_gmp.gpr:9:06: unknown project file: "gnatcoll"
gnatcoll_gmp.gpr:9:06: imported by "/opt/gnatstudio/share/gpr/gnatcoll_gmp.gpr"
gnatcoll_gmp.gpr:9:06: imported by "/opt/gnatstudio/share/gpr/libadalang.gpr"
gnatcoll_gmp.gpr:9:06: imported by "/home/xgdfalcon/source/generate_schemas/lal_test.gpr"
gprbuild: "lal_test.gpr" processing failed 
```
I also tried on latest Ubuntu with same results.

Any help appreciated

**Comment by pmderodat** [comment]
Hello,

Could you clarify how you installed Libadalang? Also, assuming you installed a binary package (as opposed to building Libadalang yourself), could you make sure that you installed the corresponding GNAT compiler?

**Comment by xgdfalcon** [comment]
I built it myself following the instructions to ensure I had the correct compiler.  Which is why I believe it is an instructions issue, not a code issue.

I have no problem building other ada projects, but cannot build the tutorial.

**Comment by pmderodat** [comment]
Understood, thank you. My hypothesis for now is that the compiler you used to build Libadalang is not the one you are using to build the tutorial project. Let’s check that: in the same shell session (no further environment variable changes after the initial setup), could you:

* Run `gnatls -v` and post its output here.
* Try to re-build Libadalang. This build needs GNATCOLL, so I would expect the build to no longer be possible.
* If the build succeeds, re-try, still in the same shell session, to rebuild the tutorial project.

In addition, do you remember what you did to build & install GNATCOLL?

**Comment by pmderodat** [comment]
Hello,

We had no feedback from you in the last month, and our best guess for now is that there is a setup issue on your side, so we’ll close this issue. Now, don’t hesitate to followup here in the future if need be. Thanks!
