### ISSUE TITLE
Name Resolution: Subprogram Renaming Declarations not resolved

### ISSUE THREAD

**Issue by Roldak** [AdaCore/libadalang#57]
```
function F(a: A) return B renames G;
```
`G` is not resolved.

**Comment by raph-amiard** [comment]
Well in that case it is expected since G doesn't exist :P

Renamings are implemented so you probably hit a bug, in which case, please submit a more complete reproducer :)

**Comment by raph-amiard** [comment]
@Roldak I don't remember the status of this, is there still something to do here ?

**Comment by Roldak** [comment]
No it's working now (IIRC) :+1:
