### ISSUE TITLE
User manual: calling libadalang from Python on macOS

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#572]
In the User Manual, Section 6 (Python API Tutorial) says we have to use 2.7, but it seems to work just fine with 3.7 (not surprising I suppose, since we have to use 3.8 to build libadalang; I was just checking whether I needed to update other Python-using projects).

On macOS (at least), I have to specify `[DY]LD_LIBRARY_PATH`: e.g.
```
export LD_LIBRARY_PATH=~/local/libadalang/lib      # temporary installation
python test.py ~/cortex-gnat-rts/common/gcc8/*
```

This isn’t mentioned in the User Manual.

**Comment by pmderodat** [comment]
Hello Simon,

Thank you for reporting this other Python version inconsistency, we’ll fix it shortly.

Regarding the environment variables updates, it seems indeed that the manual to build and install Libadalang lacks the information to  update environment variables. We’ll improve the documentation.

Sorry if this what you meant, but it’s not clear to me whether you need to set  both `DYLD_LIBRARY_PATH` and `LIBRARY_PATH` on macOS, or if only the latter is enough: could you confirm what the requirement is exactly?

**Comment by simonjwright** [comment]
The man pages for _dyld_ say to use `DYLD_LIBRARY_PATH`, but nowadays `LD_LIBRARY_PATH` (*not* `LIBRARY_PATH`) works fine.

**Comment by pmderodat** [comment]
Ok, thank you! I prefer to ask, because our support for macOS is very limited, and in particular we (AdaCore) don’t officially support shared libraries for Langkit/Libadalang on this platform. That being said, we’re open to contributions to keep Langkit/Libadalang working on that platform: don’t hesitate to submit fixes if you need them.

**Comment by simonjwright** [comment]
OK, but if you don’t support shared libraries the Python bindings are ruled out?

**Comment by pmderodat** [comment]
Yes, Libadalang’s Python bindings rely on shared libraries. We have updated the documentation to the best of our knowledge so far regarding required environment variable updates, and have clarified Python version requirements (3.7+ to build LAL, 2.7+ or 3.7+ to use the Python bindings).
