### ISSUE TITLE
User Manual: Core Concepts

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#574]
The set of project & source files in section 3.4.1, Aggregate Projects, doesn’t make sense (well, I suppose it does if you leave out the `main` part - I can’t see any way you could actually compile it as-is).

Also, the numbered subsections 1 & 2 need rewording - remove the 'Either' at the start of each - unless there’s a missing 'or'?

**Comment by pmderodat** [comment]
Hello @simonjwright,

Thank you for reporting this obscure aggregate project example. It made sense to me when I wrote it, but now I agree that it needs to be clarified. We’ll update it to present an aggregate project that shows the discussed ambiguity *and* builds all sources.

Also thank you for reporting the language issue. We’ll fix it accordingly.

**Comment by pmderodat** [comment]
Hello again,

I opened #584 to enhance this part of the documentation. Please let me know if you think we should improve it further. Thank you!
