### ISSUE TITLE
Resolution of overloaded "=" should also overload "/="

### ISSUE THREAD

**Issue by ludogauthier** [AdaCore/libadalang#62]
Hello,

If we overload the operator "=" with a function returning a Boolean it should also implicitly overload the "/=" operator. This case does not seems to be supported by libAdaLang at the moment.

Thanks.

```Ada
#!/usr/bin/env python
import libadalang as lal

str2ada_ctx = lal.AnalysisContext('utf-8')
def str2ada(string):
    unit = str2ada_ctx.get_from_buffer("", string)
    unit.populate_lexical_env()
    return unit.root

relationops = str2ada("""
   procedure P is
      function "="(I,J: Integer) return Boolean is (True);
      B1 : constant Boolean := Integer'(3) = Integer'(4); 
      B2 : constant Boolean := Integer'(3) /= Integer'(4); 
   begin null;   end;
""").findall(lal.RelationOp);

for relop in relationops:
    assert relop.p_resolve_names
    print relop.f_op, "reference", relop.p_referenced_decl
```

**Comment by raph-amiard** [comment]
Hello Ludovic,

Indeed this is not supported, but it is not clear to me what you are expecting, would you expect the call to /= to resolve to the "=" overload ?

Thanks in advance

**Comment by ludogauthier** [comment]
> would you expect the call to /= to resolve to the "=" overload ?

Yes, I think this is what I would expect. But if you have another proposition it's OK for me.
Thanks.

**Comment by raph-amiard** [comment]
Ok, this is now implemented!
