### ISSUE TITLE
Build instructions need wheel package

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#708]
For macOS, Python 3.8.6, the instructions in `/user_manual/building.rst` should tell us to install the python `wheel` package into a new venv before building Langkit.

If `wheel` isn’t installed, when you attempt to **reinstall** Langkit you get
```
Using legacy 'setup.py install' for Langkit, since package 'wheel' is not installed.
Installing collected packages: Langkit
  Attempting uninstall: Langkit
    Found existing installation: Langkit 0.1.dev0
ERROR: Cannot uninstall 'Langkit'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by pmderodat** [comment]
Hello @simonjwright,

Thank you for reporting this. We’ll add `wheel` to the `REQUIREMENTS.dev` file, used to install Python dependencies before installing Langkit in the build instructions. Please let us know if this is not enough.
