### ISSUE TITLE
cannot do node.children[-1]

### ISSUE THREAD

**Issue by jotd666** [AdaCore/libadalang#8]
python is great for pragmatic shortcuts, like getting the last item of list by doing my_list[-1]

unfortunately, it doesn't work with AdaNodeLists as provided by libadalang so I have to do: node.children[len(node.children)-1] and I hate that :)

**Comment by pmderodat** [comment]
This is a good point, thank you for suggesting that. We will enhance Langkit to make this possible in Libadalang.

**Comment by pmderodat** [comment]
This should work, now!
