### ISSUE TITLE
Error when installing Langkit with pip

### ISSUE THREAD

**Issue by zackboll** [AdaCore/libadalang#9]
Installing libadalang 
`  $ virtualenv env
  $ source env/bin/activate
  $ pip install -r REQUIREMENTS.dev`

Generates the following error in regards langkit setup

> Downloading/unpacking Mako==1.0.1 (from -r REQUIREMENTS.dev (line 1))
>   Downloading Mako-1.0.1.tar.gz (473kB): 473kB downloaded
>   Running setup.py (path:/tmp/pip-build-BO9r_2/Mako/setup.py) egg_info for package Mako
>     
>     warning: no files found matching '*.xml' under directory 'examples'
>     warning: no files found matching '*.mako' under directory 'examples'
>     warning: no files found matching 'ez_setup.py'
>     no previously-included directories found matching 'doc/build/output'
> Downloading/unpacking PyYAML==3.11 (from -r REQUIREMENTS.dev (line 2))
>   Downloading PyYAML-3.11.zip (371kB): 371kB downloaded
>   Running setup.py (path:/tmp/pip-build-BO9r_2/PyYAML/setup.py) egg_info for package PyYAML
>     
> Downloading/unpacking Sphinx==1.3.1 (from -r REQUIREMENTS.dev (line 3))
>   Downloading Sphinx-1.3.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
> Downloading/unpacking coverage==3.7.1 (from -r REQUIREMENTS.dev (line 4))
>   Downloading coverage-3.7.1.tar.gz (284kB): 284kB downloaded
>   Running setup.py (path:/tmp/pip-build-BO9r_2/coverage/setup.py) egg_info for package coverage
>     
>     warning: no previously-included files matching '*.pyc' found anywhere in distribution
> Downloading/unpacking enum==0.4.6 (from -r REQUIREMENTS.dev (line 5))
>   Downloading enum-0.4.6.tar.gz
>   Running setup.py (path:/tmp/pip-build-BO9r_2/enum/setup.py) egg_info for package enum
>     
> Downloading/unpacking enum34==1.1.2 (from -r REQUIREMENTS.dev (line 6))
>   Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
>   Running setup.py (path:/tmp/pip-build-BO9r_2/enum34/setup.py) egg_info for package enum34
>     
> Downloading/unpacking psutil==3.4.2 (from -r REQUIREMENTS.dev (line 7))
>   Downloading psutil-3.4.2.tar.gz (274kB): 274kB downloaded
>   Running setup.py (path:/tmp/pip-build-BO9r_2/psutil/setup.py) egg_info for package psutil
>     
>     warning: no previously-included files matching '*' found under directory 'docs/_build'
> Downloading/unpacking sphinx-rtd-theme==0.1.9 (from -r REQUIREMENTS.dev (line 8))
>   Downloading sphinx_rtd_theme-0.1.9-py2-none-any.whl (693kB): 693kB downloaded
> Downloading/unpacking funcy==1.7.1 (from -r REQUIREMENTS.dev (line 9))
>   Downloading funcy-1.7.1.tar.gz
>   Running setup.py (path:/tmp/pip-build-BO9r_2/funcy/setup.py) egg_info for package funcy
>     
> Obtaining langkit from git+https://github.com/AdaCore/langkit.git#egg=langkit (from -r REQUIREMENTS.dev (line 10))
>   Cloning https://github.com/AdaCore/langkit.git to ./env/src/langkit
>   Running setup.py (path:/home/zboll/git/libadalang/env/src/langkit/setup.py) egg_info for package langkit
>     error in Langkit setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
>     Complete output from command python setup.py egg_info:
>     error in Langkit setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /home/zboll/git/libadalang/env/src/langkit
> Storing debug log for failure in /home/zboll/.pip/pip.log

**Comment by pmderodat** [comment]
Hello @zackboll,

Thank you very much for this bug report. We can reproduce and are working on a fix. In the meantime, you can work around this issue doing the following:

* install all packages in `REQUIREMENTS.dev` except Langkit;
* create a git clone of Langkit at the root of the Libadalang repository.

Sorry for the inconvenience!

**Comment by pmderodat** [comment]
Hello again,

I just pushed a fix in Langkit: <https://github.com/AdaCore/langkit/commit/d11c8a5d4a85743e62338cb6dfd5d3e69f587070>. The crash you reported should now be gone.

Thanks again for your report!
