### ISSUE TITLE
Question: C# Bindings

### ISSUE THREAD

**Issue by Alex-Gamper** [AdaCore/libadalang#944]
Hi Adacore

Do you have any views on a C# binding to libadalang, I appreciate it would be very Microsoft.Windows specific !
things to consider would be

1) Generation (or lack of) for platforms other than Windows
2) C#  to C/C++ interop , I was thinking of piggybacking of the already available C/C++ Api
3) Datatype marshaling, This seems to be OK

I've probably missed a few points

Alex

**Comment by DanJBower** [comment]
I'd definitely also be interested in a C# wrapper for the API, but I don't see why it'd necessarily need to be Windows specific as .NET Standard 2.0 works on the majority of platforms if it could be written to target that

**Comment by DanJBower** [comment]
Was this meant to be closed in that change?

**Comment by raph-amiard** [comment]
No it wasn't, sorry about that!

**Comment by raph-amiard** [comment]
To answer the issue: It's  not something we consider doing and maintaining ourselves outside of a support contract. However it should be "relatively" easy to do from the outside, taking inspiration from existing bindings like Python, C#, and now Java/Graal bindings.
