### ISSUE TITLE
Extra item in aggregate_assoc?

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/libadalang#947]
Consider this rule in libadalang/grammar.py:

    aggregate_assoc=Or(
        IteratedAssoc(
            "for", cut(),
            A.for_loop_param_spec, "=>",
            A.expr | A.discrete_range
        ),
        AggregateAssoc(
            Opt(A.choice_list, "=>"),
            Or(A.box_expr, A.expr)
        ),
    ),

Translating the first alternative of this to EBNF (for comparing to Ada Language Reference Manual Annex P) gives:

aggregate_assoc  :  'for' for_loop_param_spec => (expr | discrete_range)

The corresponding rule in LRM Annex P is:

iterated_component_association ::= for iterator_specification => expression

Why does libadalang have "discrete_range" here? That allows constructs like:

   A := (for I in 1 .. 5 => 1 .. 5);

which the gnat compiler rejects.

**Comment by raph-amiard** [comment]
Hi Stephen,

It does indeed look like a useless (but benine) addition to the grammar. We'll fix this! Thanks for the report

**Comment by thvnx** [comment]
Hi Stephen,

It has been fixed here: https://github.com/AdaCore/libadalang/commit/ce501bb8d9cf56b99c8f4fa31d78cfdbbe83b33e (it will be available in the next release).

Regards,
On behalf of the libadalang team.
