### ISSUE TITLE
Libadalang can't parse gnat_native 12.1.2

### ISSUE THREAD

**Issue by pjljvandelaar** [AdaCore/libadalang#950]
The [Ada-Air project](https://github.com/cwi-swat/ada-air) builds a bridge from Ada to the [Rascal metaprogramming language](https://www.rascal-mpl.org/). The [Ada-Air project](https://github.com/cwi-swat/ada-air) uses libadalang to realize its functionality. In particular, it uses version [1428b3f723859e09151404b0338d1935e548a496](https://github.com/AdaCore/Libadalang/tree/1428b3f723859e09151404b0338d1935e548a496) of libadalang.

Ada-Air has many test cases that are [run automatically](https://github.com/cwi-swat/ada-air/actions)  whenever changes are made to the code.

Ada-Air uses [Alire](https://alire.ada.dev/) to manage its dependencies. Ada-Air specified only lower bounds on its dependencies. So when gnat_native 12.1.2 was released, Ada-Air started using that version. Unfortunately, some test cases failed due to gnat_native 12.1.2: [Adding license in all files · cwi-swat/ada-air@1e9fb31 (github.com)](https://github.com/cwi-swat/ada-air/runs/7976588081?check_suite_focus=true). In particular, Ada-Air test cases broke since libadalang failed to parse the following files
* /home/runner/.config/alire/cache/dependencies/gnat_native_12.1.2_66b989b5/lib/gcc/x86_64-pc-linux-gnu/12.1.0/adainclude/s-gearop.adb
* /home/runner/.config/alire/cache/dependencies/gnat_native_12.1.2_66b989b5/lib/gcc/x86_64-pc-linux-gnu/12.1.0/adainclude/i-c.adb
* /home/runner/.config/alire/cache/dependencies/gnat_native_12.1.2_66b989b5/lib/gcc/x86_64-pc-linux-gnu/12.1.0/adainclude/a-direct.adb
* /home/runner/.config/alire/cache/dependencies/gnat_native_12.1.2_66b989b5/lib/gcc/x86_64-pc-linux-gnu/12.1.0/adainclude/i-c.ads

Limiting [Ada-Air project](https://github.com/cwi-swat/ada-air) to use gnat_native 11.2.4 removes the problem. See the [commit 0f7ab2f2a60dc801604ac08879f26203fd68f078](https://github.com/cwi-swat/ada-air/commit/0f7ab2f2a60dc801604ac08879f26203fd68f078) and associated [action run](https://github.com/cwi-swat/ada-air/actions/runs/2920504454) for more details.

Could you please improve libadalang such that it can parse gnat native 12.1.2?

Thanks in advance,

The Ada-Air team: Damien De Campos, Jurgen Vinju, and Pierre van de Laar.

**Comment by thvnx** [comment]
Hi Pierre and the Ada-Air team!

Could you provide more information about the failures you encounter when parsing these files?
(Development version of libadalang parses them successfully)

Regards,
Laurent

**Comment by pjljvandelaar** [comment]
Hi Laurent,

Thanks for the quick response!

We will investigate: 
either we will move to the latest version of libadalang to get rid of this problem (and close this issue)
or we will provide more details about the issue.

Greetings,
  Pierre
