### ISSUE TITLE
V325-006.yaml is not parseable by pyyaml

### ISSUE THREAD

**Issue by atupone** [AdaCore/libadalang#957]
The file user_manual/changes/V325-006.yaml is UTF-8 while all the other files in that directory are ASCII.

The test suite fails on that

**Comment by pmderodat** [comment]
Hello,

This is not visible on our side because utf-8 is Python’s system encoding. Hopefully we should have fixed this enforcing utf-8 to read these YAML files: please let us know if this is not enough.
