### ISSUE TITLE
Installation instructions seem outdated or lacking

### ISSUE THREAD

**Issue by Ptival** [AdaCore/libadalang#959]
I'm just trying to get the `libadalang` python bindings built, on a Linux VM (some Ubuntu), and finding it problematic.

I have done the following:
- Installed, via the `apt` package manager, all of `gnat gprbuild libgnatcoll19-dev libgnatcoll-gmp19-dev libgnatcoll-iconv19-dev`,
- Created a Python virutal environment, installed `REQUIREMENTS.dev` in there,
- Checked out and installed the Langkit Python package.

But when trying to build the "langkit support", I get the following error:
```
langkit_support.gpr:4:06: imported project file "adasat" not found
```

Nothing in the installation instructions mention `adasat`.

From [this CI action](https://github.com/AdaCore/libadalang/blob/d34545e1a63c110dac6149c04c60fad537f511ce/.github/workflows/build-binaries.yml#L67-L71), I gather it's [this](https://github.com/AdaCore/adasat), but I tried checking it out in the same location, and it doesn't help.

I can definitely build AdaSAT, but then langkit's `manage.py` seems to do nothing with it. Supposedly I'd need to add it to my `GPR_PROJECT_PATH`, but at that point it seems I'm deviating from the intended installation setup.

**Comment by pmderodat** [comment]
Hello,

Thank you for reporting this omission: we’ll complete our build instructions accordingly.

> * Installed, via the `apt` package manager, all of `gnat gprbuild libgnatcoll19-dev libgnatcoll-gmp19-dev libgnatcoll-iconv19-dev`,

This will work for the 19 release of Libadalang, but if you are trying to build the current `master` branch, you should build and install the `master` branches for all library dependencies as well (xmlada, libgpr, gnatcoll, …).

> I can definitely build AdaSAT, but then langkit's `manage.py` seems to do nothing with it. Supposedly I'd need to add it to my `GPR_PROJECT_PATH`, but at that point it seems I'm deviating from the intended installation setup.

Right, or even better: install AdaSAT with gprinstall.
